"""
从 config/funds.json 生成 web/js/config.js 中的派生常量段。
原 gen_frontend_config.py 逻辑搬迁，import core+sources。
"""
import json

from core.constants import ROOT_DIR, CONFIG_DIR

CFG_FP = CONFIG_DIR / "funds.json"
JS_FP = ROOT_DIR / "web" / "js" / "config.js"

START = "// AUTO-GENERATED CONFIG START"
END = "// AUTO-GENERATED CONFIG END"


def _js_obj(d: dict, indent: int = 2) -> str:
    return json.dumps(d, ensure_ascii=False, indent=indent)


def build_generated_block(cfg: dict) -> str:
    starred = cfg.get("starred", [])
    company_brand = cfg.get("company_brand", {})
    passive_override = cfg.get("passive_override", {})

    lines = [
        START,
        "// DO NOT EDIT: generated by scripts/pipeline/codegen.py from config/funds.json",
        f"const OFFSHORE_STARRED = new Set({_js_obj(starred)});",
        "",
        f"const COMPANY_BRAND = {_js_obj(company_brand)};",
        "",
        f"const PASSIVE_HOLDINGS_OVERRIDE = {_js_obj(passive_override)};",
        END,
    ]
    return "\n".join(lines)


def main():
    cfg = json.loads(CFG_FP.read_text(encoding="utf-8"))
    generated = build_generated_block(cfg)

    content = JS_FP.read_text(encoding="utf-8")
    if START in content and END in content:
        left = content.split(START)[0]
        right = content.split(END)[1]
        new_content = left + generated + right
    else:
        anchor = "const SHARE_CLASS_ORDER = {'A':0,'C':1,'D':2,'E':3,'F':4,'H':5,'I':6,'默认':7,'LOF':8,'A(后端)':9};"
        if anchor not in content:
            raise RuntimeError("config.js 中未找到注入锚点")
        new_content = content.replace(anchor, anchor + "\n\n" + generated)

    JS_FP.write_text(new_content, encoding="utf-8")
    print("✅ 已生成 config.js 派生常量段")


if __name__ == "__main__":
    main()
