#!/usr/bin/env python3
"""
从 config/funds.json 生成 web/js/config.js 中的派生常量段：
- OFFSHORE_STARRED
- COMPANY_BRAND
- PASSIVE_HOLDINGS_OVERRIDE
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
CFG_FP = ROOT / "config" / "funds.json"
JS_FP = ROOT / "web" / "js" / "config.js"

START = "// AUTO-GENERATED CONFIG START"
END = "// AUTO-GENERATED CONFIG END"


def _js_obj(d: dict, indent: int = 2) -> str:
    s = json.dumps(d, ensure_ascii=False, indent=indent)
    return s


def build_generated_block(cfg: dict) -> str:
    starred = cfg.get("starred", [])
    company_brand = cfg.get("company_brand", {})
    passive_override = cfg.get("passive_override", {})

    lines = [
        START,
        "// DO NOT EDIT: generated by scripts/gen_frontend_config.py from config/funds.json",
        f"const OFFSHORE_STARRED = new Set({_js_obj(starred)});",
        "",
        f"const COMPANY_BRAND = {_js_obj(company_brand)};",
        "",
        f"const PASSIVE_HOLDINGS_OVERRIDE = {_js_obj(passive_override)};",
        END,
    ]
    return "\n".join(lines)


def main():
    cfg = json.loads(CFG_FP.read_text(encoding="utf-8"))
    generated = build_generated_block(cfg)

    content = JS_FP.read_text(encoding="utf-8")
    if START in content and END in content:
        left = content.split(START)[0]
        right = content.split(END)[1]
        new_content = left + generated + right
    else:
        # 首次注入：插在 SHARE_CLASS_ORDER 后，保持变量被下方引用
        anchor = "const SHARE_CLASS_ORDER = {'A':0,'A(后端)':1,'C':2,'D':3,'E':4,'F':5,'H':6,'I':7,'默认':8,'LOF':9};"
        if anchor not in content:
            raise RuntimeError("config.js 中未找到注入锚点")
        new_content = content.replace(anchor, anchor + "\n\n" + generated)

    JS_FP.write_text(new_content, encoding="utf-8")
    print("✅ 已生成 config.js 派生常量段")


if __name__ == "__main__":
    main()
